name: Quality Assurance

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
